services:
  trading-bot:
    build: .
    container_name: quantitative_trading_bot
    volumes:
      - .:/app
    ports:
      - "8088:8088"
    environment:
      - PYTHONUNBUFFERED=1
    command: python web/app.py
